version: '3'

services:
  test:
    image: node:latest
    depends_on:
      - postgres
      - mssql
    command: ./wait-for-it.sh postgres:5432 -- ./wait-for-it.sh mssql:1433 -- npm test
    environment:
      NODE_ENV: development
    volumes:
      - ./:/app
    working_dir: /app

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password

  mssql:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Passw0rd*
