version: "3"

services:
  test:
    build: .
    depends_on:
      - postgres
      - mssql
    command: ./wait-for-it.sh postgres:5432 -- ./wait-for-it.sh mssql:1433 -- npm test
    environment:
      NODE_ENV: development
    volumes:
      - ./coverage/:/app/coverage

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU13-ubuntu-20.04
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Passw0rd*
