version: "3"

services:
  test:
    build: .
    depends_on:
      - postgres
      - mssql
      - mysql
    command: ./wait-for-it.sh postgres:5432 -- ./wait-for-it.sh mssql:1433 -- ./wait-for-it.sh mysql:3306 -- npm test
    environment:
      NODE_ENV: development
    volumes:
      - ./coverage/:/app/coverage

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test

  mssql:
    image: mcr.microsoft.com/azure-sql-edge
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Passw0rd*
